# Generated by Django 5.2.8 on 2026-06-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgen', '0004_alter_user_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB'), ('AB', 'AB')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
    ]
